/**
 * GLIDE — lane-runner, pure config. Generated by `npm run new-game`.
 * Tune the numbers below; nothing else needs to change.
 */
import { laneRunnerEngine } from '../engines/laneRunner';
import type { LaneRunnerCfg } from '../engines/laneRunner';
import type { EngineModule } from '../types';

export const glide: EngineModule<LaneRunnerCfg> = {
  meta: {
    id: 'glide',
    name: 'GLIDE',
    code: 'GLD',
    family: 'SWIPE',
    unit: 'm',
    lowerIsBetter: false,
    blurb: 'Ride the gaps. It never slows down.',
  },
  engine: 'lane-runner',
  // Faster and tighter than DODGE, and four lanes instead of three — same
  // engine, different game.
  config: {
    ...laneRunnerEngine.defaults,
    lanes: 4,
    speed0: 160,
    fallBase: 300,
    spawnMax: 0.6,
    spawnMin: 0.28,
  },
};
