#!/usr/bin/env node
/**
 * new-game — scaffold a game in one file.
 *
 *   npm run new-game -- --name GLIDE --code GLD --family SWIPE --unit m --engine lane-runner
 *   npm run new-game        (no args → interactive prompts)
 *
 * Writes games/catalogue/<id>.ts from the engine's defaults and registers it in
 * games/catalogue/index.ts. Nothing else in the app changes. This is the whole
 * reason game #50 costs what game #12 cost.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createInterface } from 'node:readline/promises';
import { stdin, stdout } from 'node:process';

const HERE = dirname(fileURLToPath(import.meta.url));
const CATALOGUE_DIR = join(HERE, '..', 'games', 'catalogue');
const INDEX = join(CATALOGUE_DIR, 'index.ts');

const FAMILIES = ['TAP', 'SWIPE', 'TIMING', 'NUMBERS', 'MEMORY'];

// Implemented engines: how to import them and their config type. Engines not
// listed here can still be named, but the game is written with an empty config
// and stays unplayable until the engine lands (a stage-09 batch).
const ENGINES = {
  'needle-band': { file: 'needleBand', varName: 'needleBandEngine', cfg: 'NeedleBandCfg' },
  'lane-runner': { file: 'laneRunner', varName: 'laneRunnerEngine', cfg: 'LaneRunnerCfg' },
  'target-tap': { file: 'targetTap', varName: 'targetTapEngine', cfg: 'TargetTapCfg' },
};
const ALL_ENGINE_IDS = [
  'needle-band', 'lane-runner', 'target-tap',
  'orbit-timing', 'grid-merge', 'number-pick', 'memory-recall', 'trace-path',
];

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (key === 'lower') out.lower = true;
      else if (next && !next.startsWith('--')) { out[key] = next; i++; }
      else out[key] = true;
    }
  }
  return out;
}

async function prompt(fields) {
  const rl = createInterface({ input: stdin, output: stdout });
  const out = {};
  for (const [key, label] of fields) out[key] = (await rl.question(`${label}: `)).trim();
  rl.close();
  return out;
}

function fail(msg) {
  console.error(`✗ ${msg}`);
  process.exit(1);
}

function toId(name) {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '');
}

function moduleSource({ id, name, code, family, unit, lower, blurb, engine }) {
  const known = ENGINES[engine];
  const varName = `${id}`;
  const metaBlock = `  meta: {
    id: '${id}',
    name: '${name}',
    code: '${code}',
    family: '${family}',
    unit: '${unit}',
    lowerIsBetter: ${lower ? 'true' : 'false'},
    blurb: '${blurb.replace(/'/g, "\\'")}',
  },`;

  if (known) {
    return `/**
 * ${name} — ${engine}, pure config. Generated by \`npm run new-game\`.
 * Tune the numbers below; nothing else needs to change.
 */
import { ${known.varName} } from '../engines/${known.file}';
import type { ${known.cfg} } from '../engines/${known.file}';
import type { EngineModule } from '../types';

export const ${varName}: EngineModule<${known.cfg}> = {
${metaBlock}
  engine: '${engine}',
  config: { ...${known.varName}.defaults },
};
`;
  }

  return `/**
 * ${name} — ${engine} (engine not implemented yet; ${name} stays unplayable and
 * shows the placeholder until the engine lands). Generated by \`npm run new-game\`.
 */
import type { EngineModule } from '../types';

export const ${varName}: EngineModule = {
${metaBlock}
  engine: '${engine}',
  config: {},
};
`;
}

function register(id) {
  let src = readFileSync(INDEX, 'utf8');
  if (src.includes(`from './${id}'`)) fail(`${id} is already registered in catalogue/index.ts`);

  // Insert the import after the last relative import line.
  const importLine = `import { ${id} } from './${id}';`;
  const lines = src.split('\n');
  let lastImport = -1;
  for (let i = 0; i < lines.length; i++) if (/^import .* from '\.\/.+';$/.test(lines[i])) lastImport = i;
  if (lastImport === -1) fail('could not find the import block in catalogue/index.ts');
  lines.splice(lastImport + 1, 0, importLine);
  src = lines.join('\n');

  // Insert the entry before the object's closing brace.
  src = src.replace(/(export const CATALOGUE[^{]*\{)([\s\S]*?)(\n\};)/, (_m, head, body, tail) => {
    const entry = `\n  ${id},`;
    return `${head}${body}${entry}${tail}`;
  });

  writeFileSync(INDEX, src);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  let data = {
    name: args.name,
    code: args.code,
    family: args.family,
    unit: args.unit,
    engine: args.engine,
    blurb: args.blurb ?? 'One sentence: the rule.',
    lower: !!args.lower,
  };

  if (!data.name || !data.engine) {
    const answers = await prompt([
      ['name', 'Name (e.g. GLIDE)'],
      ['code', 'Code, 3 letters (e.g. GLD)'],
      ['family', `Family (${FAMILIES.join(' / ')})`],
      ['unit', 'Unit (e.g. m, ms, hits)'],
      ['engine', `Engine (${ALL_ENGINE_IDS.join(' / ')})`],
      ['blurb', 'Blurb (one sentence)'],
    ]);
    data = { ...data, ...answers, lower: data.lower };
  }

  data.name = (data.name || '').toUpperCase();
  const id = args.id ? toId(args.id) : toId(data.name);
  if (!id) fail('a name is required');
  data.code = (data.code || id.slice(0, 3)).toUpperCase();
  data.family = (data.family || 'TAP').toUpperCase();
  data.unit = data.unit || 'score';

  if (!FAMILIES.includes(data.family)) fail(`family must be one of ${FAMILIES.join(', ')}`);
  if (!ALL_ENGINE_IDS.includes(data.engine)) fail(`engine must be one of ${ALL_ENGINE_IDS.join(', ')}`);

  const file = join(CATALOGUE_DIR, `${id}.ts`);
  if (existsSync(file)) fail(`games/catalogue/${id}.ts already exists`);

  writeFileSync(file, moduleSource({ ...data, id }));
  register(id);

  const known = !!ENGINES[data.engine];
  console.log(`✓ wrote games/catalogue/${id}.ts and registered it`);
  console.log(known
    ? `  Tune games/catalogue/${id}.ts, then: npx expo start`
    : `  Note: the '${data.engine}' engine is not implemented yet, so ${data.name} shows the placeholder until it lands.`);
  console.log('  Run: npx tsc --noEmit');
}

main().catch((e) => fail(e.message));
